version: 2

models:
  - name: tutorials
    description: "{{ doc('tutorials') }}"
    columns:
      - name: id
        type: integer
        description: "The identification number of the hands-on tutorial"

      - name: speaker_id
        type: integer
        description: "The primary key for this table"

      - name: title
        type: string
        description: "The title of the hands-on tutorial"

      - name: summary
        type: string
        description: "Short text description of the hands-on tutorial content and details"

      - name: schedule
        type: string
        description: "The time slot of the hands-on tutorial in format HH:MM-HH:MM"

      - name: duration
        type: string
        description: "The duration, in minutes, of the hands-on tutorial"
